# Generated by Django 2.1.15 on 2020-04-14 18:50

import backend.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=120, verbose_name='company_name')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Finances',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1960), backend.models.max_value_current_year], verbose_name='year')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='amount')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Company')),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='entry_name')),
                ('isExpense', models.BooleanField(verbose_name='is_expense')),
            ],
        ),
        migrations.AddField(
            model_name='finances',
            name='line_item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.LineItem'),
        ),
    ]
